name: Deploy Desa

on:
  push:
    branches:
      - desa

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/bullcrux_backend_desa
            ./deploy.sh
